server:
  port: 8080

spring:
 application:
   name: hsd-end-project
 datasource:
   url: jdbc:mysql://localhost:3306/hsd_end_project
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: wh232629


mybatis-plus:
  type-aliases-package: com.angkish.pojo.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id


sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: angkish12345678901234567890123456
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: token